name: publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: 1.73.0

      - name: publish
        uses: actions-rs/toolchain@v1.0.6
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_TOKEN }}
